apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-nginx-deploy
spec:
  selector:
    matchLabels:
      app: python-nginx
  replicas: 1            # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: python-nginx
    spec:
      containers:
      - name: python-nginx
        # image: nginx:1.22.1
        image: idsvnasia/python-nginx:v1.0
        ports:
        - containerPort: 80
